-- Dungeon Descent — schema MariaDB
-- Aplicado automaticamente no boot (server/migrate.js).

CREATE DATABASE IF NOT EXISTS dungeon_descent
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE dungeon_descent;

CREATE TABLE IF NOT EXISTS players (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_key CHAR(36) NOT NULL,
  discord_id VARCHAR(32) NULL,
  display_name VARCHAR(64) NULL,
  global_name VARCHAR(64) NULL,
  avatar VARCHAR(128) NULL,
  essences INT UNSIGNED NOT NULL DEFAULT 0,
  gold BIGINT UNSIGNED NOT NULL DEFAULT 0,
  max_floor_record INT UNSIGNED NOT NULL DEFAULT 0,
  last_login DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_players_player_key (player_key),
  UNIQUE KEY uq_players_discord_id (discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS characters (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id BIGINT UNSIGNED NOT NULL,
  class_id VARCHAR(32) NOT NULL,
  level INT UNSIGNED NOT NULL DEFAULT 1,
  xp INT UNSIGNED NOT NULL DEFAULT 0,
  str_stat INT NOT NULL DEFAULT 0,
  con_stat INT NOT NULL DEFAULT 0,
  agi_stat INT NOT NULL DEFAULT 0,
  dex_stat INT NOT NULL DEFAULT 0,
  int_stat INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_characters_player_class (player_id, class_id),
  CONSTRAINT fk_characters_player
    FOREIGN KEY (player_id) REFERENCES players (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS character_equipment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  character_id BIGINT UNSIGNED NOT NULL,
  slot VARCHAR(32) NOT NULL,
  item_key VARCHAR(64) NOT NULL,
  item_level INT UNSIGNED NOT NULL DEFAULT 1,
  rarity VARCHAR(16) NOT NULL DEFAULT 'common',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_character_equipment_slot (character_id, slot),
  CONSTRAINT fk_character_equipment_character
    FOREIGN KEY (character_id) REFERENCES characters (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS character_skills (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  character_id BIGINT UNSIGNED NOT NULL,
  skill_key VARCHAR(64) NOT NULL,
  skill_level INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_character_skills (character_id, skill_key),
  CONSTRAINT fk_character_skills_character
    FOREIGN KEY (character_id) REFERENCES characters (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permanent_upgrades (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id BIGINT UNSIGNED NOT NULL,
  upgrade_key VARCHAR(64) NOT NULL,
  level INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_permanent_upgrades_player_key (player_id, upgrade_key),
  CONSTRAINT fk_permanent_upgrades_player
    FOREIGN KEY (player_id) REFERENCES players (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS player_stats (
  player_id BIGINT UNSIGNED NOT NULL,
  runs INT UNSIGNED NOT NULL DEFAULT 0,
  deaths INT UNSIGNED NOT NULL DEFAULT 0,
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  gold_earned_total BIGINT UNSIGNED NOT NULL DEFAULT 0,
  play_time_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_player_stats_player
    FOREIGN KEY (player_id) REFERENCES players (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS player_settings (
  player_id BIGINT UNSIGNED NOT NULL,
  settings_json JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (player_id),
  CONSTRAINT fk_player_settings_player
    FOREIGN KEY (player_id) REFERENCES players (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Evolutivos para bases já existentes
ALTER TABLE players ADD COLUMN IF NOT EXISTS discord_id VARCHAR(32) NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS global_name VARCHAR(64) NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS avatar VARCHAR(128) NULL;
ALTER TABLE players ADD COLUMN IF NOT EXISTS gold BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS last_login DATETIME NULL;
